# THIS FILE IS MANAGED: Edit defaults in .env instead, and don't edit here
services:
  limbo-stick:
    image: espressomatic/limbo-stick:test
    container_name: limbo-stick
    restart: unless-stopped
    network_mode: host
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/espressomatic/Limbo-Stack/integration/services/Limbo-Stick-Sidecar/images/limbo-stick-logo.svg"
      net.unraid.docker.webui: "http://[IP]:[PORT:4810]/"
      net.unraid.docker.shell: "/bin/sh"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LIMBOSTICK_DATA_ROOT:-limbo_stick_config}${LIMBOSTICK_DATA_ROOT:+/limbo-stick/lidarr-config}:/config

volumes:
  limbo_stick_config:
