# THIS FILE IS MANAGED: Edit defaults in .env instead, and don't edit here
services:
  limbo-stick:
    image: espressomatic/limbo-stick:test
    container_name: limbo-stick
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LIMBOSTICK_DATA_ROOT:-limbo_stick_config}${LIMBOSTICK_DATA_ROOT:+/limbo-stick/lidarr-config}:/config

volumes:
  limbo_stick_config:
